volumes:
    mongo-data:
        external: true
services:
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo-data

  weeb_roulette:
    build:
      context: ./weeb_roulette
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./weeb_roulette:/app
    environment:
      DATABASE_URL: mongodb://root:password@mongo:27017/
      DATABASE_NAME: mongo-data
      WAIT_HOSTS: mongo:27017

  ghi:
    image: node:lts-bullseye
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
